# Information
site_name: JanICE
site_description: 'The JanICE API for computer vision'
site_author: 'Noblis'

# Repository
repo_name: 'Github'
repo_url: https://github.com/Noblis/janice

# Theme
theme: readthedocs
theme_dir: 'docs/theme/'

# Options
extra:
    version: '4.0.0'
    palette:
        primary: 'blue grey'
        accent: 'green'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    i18n:
        prev: 'Previous'
        next: 'Next'

pages:
    - Overview: 'index.md'
    - API:
        - Software Concepts: 'api/software_concepts.md'
        - Miscellaneous:
            - Functions: 'api/misc/functions.md'
        - Error Handling:
            - Overview: 'api/errors/overview.md'
            - Enums: 'api/errors/enums.md'
            - Functions: 'api/errors/functions.md'
        - I/O: 
            - Overview: 'api/io/overview.md'
            - Structs: 'api/io/structs.md'
            - Typedefs: 'api/io/typedefs.md'
            - Functions: 'api/io/functions.md'
        - Detection:
            - Overview: 'api/detection/overview.md'
            - Structs: 'api/detection/structs.md'
            - Typedefs: 'api/detection/typedefs.md'
            - Functions: 'api/detection/functions.md'
        - Enrollment:
            - Overview: 'api/enrollment/overview.md'
            - Enums: 'api/enrollment/enums.md'
            - Structs: 'api/enrollment/structs.md'
            - Typedefs: 'api/enrollment/typedefs.md'
            - Functions: 'api/enrollment/functions.md'
        - Gallery:
            - Overview: 'api/gallery/overview.md'
            - Structs: 'api/gallery/structs.md'
            - Typedefs: 'api/gallery/typedefs.md'
            - Functions: 'api/gallery/functions.md'
        - Comparison:
            - Overview: 'api/comparison/overview.md'
            - Typedefs: 'api/comparison/typedefs.md'
            - Functions: 'api/comparison/functions.md'
        - Clustering:
            - Overview: 'api/clustering/overview.md'
            - Structs: 'api/clustering/structs.md'
            - Typedefs: 'api/clustering/typedefs.md'
            - Functions: 'api/clustering/functions.md'
    - Interfaces:
        - C++: 'interfaces/cpp.md'
        - Python: 'interfaces/python.md'
        - C#: 'interfaces/csharp.md'
        - Java: 'interfaces/java.md'
    - License: 'LICENSE.md'

markdown_extensions:
    - attr_list
    - codehilite(css_class=code)
    - admonition
